server { listen 80; root /usr/share/nginx/html; index index.html;
 location /portfolio/ { proxy_pass http://portfolio:8081/; }
 location /risk/ { proxy_pass http://risk:8082/; }
 location /accounting/ { proxy_pass http://accounting:8083/; }
 location / { try_files $uri $uri/ /index.html; }
}
