ALTER SESSION SET CONTAINER=FREEPDB1;
CREATE USER portfolio IDENTIFIED BY AtlasLocal123;
CREATE USER risk IDENTIFIED BY AtlasLocal123;
CREATE USER accounting IDENTIFIED BY AtlasLocal123;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO portfolio;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO risk;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, UNLIMITED TABLESPACE TO accounting;
